### ISSUE TITLE
TypeError is returned on starting the app

### ISSUE THREAD

**Issue by tinfoil-knight** [fullstack-hy2020/patientor#10]
```bash
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
```

**How to reproduce the error?** 
```
> npm install
> npm start
```

**Comment by timiscoding** [comment]
I didn't run into this issue but I think I've experienced this error before in another repo. You have to update the `react-scripts` package. Change the version to 3.4.1 in `package.json` and rerun `npm i && npm start`
