### ISSUE TITLE
Material UI v4 is being phased out, v5 stable channel has been published

### ISSUE THREAD

**Issue by erictelkkala** [fullstack-hy2020/patientor#7]
I came across a "problem" in the task [9.17](https://fullstackopen.com/en/part9/react_with_types#exercises-9-16-9-18) of the TypeScript module.

The icons for genders are not in the [Material UI icons](https://www.npmjs.com/package/@material-ui/icons) package (all the icons for v4 can be found [here](https://v4.mui.com/components/material-icons/)), but can be found in the [v5 package](https://www.npmjs.com/package/@mui/icons-material) (full list can be found [here](https://mui.com/material-ui/material-icons/)).

The current v4 core package is written in the dependencies as `"@material-ui/core": "^4.12.3"`, but the v5 channel package is written like this `"@mui/material": "^5.10.6"`.

Should it be considered to upgrade the Material UI packages to the v5 channel?

**Comment by mluukkai** [comment]
fixed
